apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "posthog.fullname" . }}-clickhouse
  labels:
    {{- include "posthog.labels" . | nindent 4 }}
data:
  k8s-overrides.xml: |
    <clickhouse>
      <zookeeper>
        <node>
          <host>{{ include "posthog.fullname" . }}-zookeeper</host>
          <port>2181</port>
        </node>
      </zookeeper>

      <remote_servers replace="replace">
        <posthog>
          <shard>
            <replica>
              <host>{{ include "posthog.fullname" . }}-clickhouse-0.{{ include "posthog.fullname" . }}-clickhouse.{{ .Release.Namespace }}.svc.cluster.local</host>
              <port>9000</port>
            </replica>
          </shard>
        </posthog>
        <posthog_single_shard>
          <shard>
            <replica>
              <host>{{ include "posthog.fullname" . }}-clickhouse-0.{{ include "posthog.fullname" . }}-clickhouse.{{ .Release.Namespace }}.svc.cluster.local</host>
              <port>9000</port>
            </replica>
          </shard>
        </posthog_single_shard>
        <posthog_migrations>
          <shard>
            <replica>
              <host>{{ include "posthog.fullname" . }}-clickhouse-0.{{ include "posthog.fullname" . }}-clickhouse.{{ .Release.Namespace }}.svc.cluster.local</host>
              <port>9000</port>
            </replica>
          </shard>
        </posthog_migrations>
        <posthog_writable>
          <shard>
            <replica>
              <host>{{ include "posthog.fullname" . }}-clickhouse-0.{{ include "posthog.fullname" . }}-clickhouse.{{ .Release.Namespace }}.svc.cluster.local</host>
              <port>9000</port>
            </replica>
          </shard>
        </posthog_writable>
        <posthog_primary_replica>
          <shard>
            <replica>
              <host>{{ include "posthog.fullname" . }}-clickhouse-0.{{ include "posthog.fullname" . }}-clickhouse.{{ .Release.Namespace }}.svc.cluster.local</host>
              <port>9000</port>
            </replica>
          </shard>
        </posthog_primary_replica>
        <ai_events>
          <shard>
            <replica>
              <host>{{ include "posthog.fullname" . }}-clickhouse-0.{{ include "posthog.fullname" . }}-clickhouse.{{ .Release.Namespace }}.svc.cluster.local</host>
              <port>9000</port>
            </replica>
          </shard>
        </ai_events>
        <aux>
          <shard>
            <replica>
              <host>{{ include "posthog.fullname" . }}-clickhouse-0.{{ include "posthog.fullname" . }}-clickhouse.{{ .Release.Namespace }}.svc.cluster.local</host>
              <port>9000</port>
            </replica>
          </shard>
        </aux>
        <ops>
          <shard>
            <replica>
              <host>{{ include "posthog.fullname" . }}-clickhouse-0.{{ include "posthog.fullname" . }}-clickhouse.{{ .Release.Namespace }}.svc.cluster.local</host>
              <port>9000</port>
            </replica>
          </shard>
        </ops>
        <sessions>
          <shard>
            <replica>
              <host>{{ include "posthog.fullname" . }}-clickhouse-0.{{ include "posthog.fullname" . }}-clickhouse.{{ .Release.Namespace }}.svc.cluster.local</host>
              <port>9000</port>
            </replica>
          </shard>
        </sessions>
      </remote_servers>
    </clickhouse>
