{{- if eq .Values.clickhouse.type "internal" }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "posthog.fullname" . }}-clickhouse
  labels:
    {{- include "posthog.labels" . | nindent 4 }}
    {{- include "posthog.selectorLabels" (dict "context" . "component" "clickhouse") | nindent 4 }}
spec:
  replicas: 1
  serviceName: {{ include "posthog.fullname" . }}-clickhouse
  selector:
    matchLabels:
      {{- include "posthog.selectorLabels" (dict "context" . "component" "clickhouse") | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "posthog.labels" . | nindent 8 }}
        {{- include "posthog.selectorLabels" (dict "context" . "component" "clickhouse") | nindent 8 }}
    spec:
      containers:
        - name: clickhouse
          image: {{ include "posthog.clickhouseImage" . }}
          ports:
            - name: http
              containerPort: 8123
            - name: native
              containerPort: 9000
          env:
            - name: CLICKHOUSE_SKIP_USER_SETUP
              value: "1"
            - name: KAFKA_HOSTS
              value: {{ include "posthog.fullname" . }}-kafka:9092
          readinessProbe:
            exec:
              command: ["wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8123/ping"]
            initialDelaySeconds: 10
            periodSeconds: 3
            timeoutSeconds: 10
            failureThreshold: 10
          livenessProbe:
            exec:
              command: ["wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8123/ping"]
            initialDelaySeconds: 30
            periodSeconds: 10
          volumeMounts:
            - name: clickhouse-data
              mountPath: /var/lib/clickhouse
  volumeClaimTemplates:
    - metadata:
        name: clickhouse-data
      spec:
        {{- include "posthog.pvcSpec" (dict "size" .Values.clickhouse.persistence.size "storageClass" .Values.clickhouse.persistence.storageClass) | nindent 8 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "posthog.fullname" . }}-clickhouse
  labels:
    {{- include "posthog.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8123
      targetPort: http
    - name: native
      port: 9000
      targetPort: native
  selector:
    {{- include "posthog.selectorLabels" (dict "context" . "component" "clickhouse") | nindent 4 }}
{{- end }}
