apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "posthog.fullname" . }}-zookeeper
  labels:
    {{- include "posthog.labels" . | nindent 4 }}
    {{- include "posthog.selectorLabels" (dict "context" . "component" "zookeeper") | nindent 4 }}
spec:
  replicas: 1
  serviceName: {{ include "posthog.fullname" . }}-zookeeper
  selector:
    matchLabels:
      {{- include "posthog.selectorLabels" (dict "context" . "component" "zookeeper") | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "posthog.labels" . | nindent 8 }}
        {{- include "posthog.selectorLabels" (dict "context" . "component" "zookeeper") | nindent 8 }}
    spec:
      {{- include "posthog.scheduling" . | nindent 6 }}
      containers:
        - name: zookeeper
          image: {{ include "posthog.infraImage" .Values.images.zookeeper }}
          ports:
            - name: client
              containerPort: 2181
          volumeMounts:
            - name: zookeeper-data
              mountPath: /data
            - name: zookeeper-datalog
              mountPath: /datalog
            - name: zookeeper-logs
              mountPath: /logs
  volumeClaimTemplates:
    - metadata:
        name: zookeeper-data
      spec:
        {{- include "posthog.pvcSpec" (dict "size" .Values.zookeeper.persistence.size "storageClass" .Values.zookeeper.persistence.storageClass) | nindent 8 }}
    - metadata:
        name: zookeeper-datalog
      spec:
        {{- include "posthog.pvcSpec" (dict "size" .Values.zookeeper.persistence.size "storageClass" .Values.zookeeper.persistence.storageClass) | nindent 8 }}
    - metadata:
        name: zookeeper-logs
      spec:
        {{- include "posthog.pvcSpec" (dict "size" .Values.zookeeper.persistence.size "storageClass" .Values.zookeeper.persistence.storageClass) | nindent 8 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "posthog.fullname" . }}-zookeeper
  labels:
    {{- include "posthog.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: client
      port: 2181
      targetPort: client
  selector:
    {{- include "posthog.selectorLabels" (dict "context" . "component" "zookeeper") | nindent 4 }}
